In [78]:
import torch
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

# Tensors- 2D

In [79]:
a = [[1,3,5],[3,2,1],[2,4,8]]
tensor_a =  torch.tensor(a)
tensor_a

tensor([[1, 3, 5],
        [3, 2, 1],
        [2, 4, 8]])

In [80]:
# Checking the dimension of a tensor
tensor_a.ndimension()

2

In [81]:
# Shape represents the no of row Vs. no of Columns
tensor_a.shape

torch.Size([3, 3])

In [82]:
tensor_a.size()

torch.Size([3, 3])

In [83]:
# No of elements in tensor - (no.of Col * No.of rows)
tensor_a.numel()

9

In [84]:
[tensor_a[0], tensor_a[2], tensor_a[2,2].item(), tensor_a.type ,tensor_a.type(), tensor_a.dtype, tensor_a.size()]

[tensor([1, 3, 5]),
 tensor([2, 4, 8]),
 8,
 <function Tensor.type>,
 'torch.LongTensor',
 torch.int64,
 torch.Size([3, 3])]

### Numpy array

In [102]:
np_arry =  np.array([[1,2,3],[3,2,1]])
print(type(np_arry))
np_arry

<class 'numpy.ndarray'>


array([[1, 2, 3],
       [3, 2, 1]])

In [103]:
# Converting numpy to tensor 
torch_tensor =  torch.from_numpy(np_arry)
torch_tensor

tensor([[1, 2, 3],
        [3, 2, 1]], dtype=torch.int32)

In [104]:
# Converting tensor back to numpy
tensor_to_numpy = torch_tensor.numpy()
print(tensor_to_numpy.dtype)
tensor_to_numpy

int32


array([[1, 2, 3],
       [3, 2, 1]])

### Pandas

In [112]:
df = pd.DataFrame({'A':[1, 3, 5],'B':[3,2, 1]})
df

A  B
0  1  3
1  3  2
2  5  1

In [113]:
pd_to_torch =  torch.tensor(df.values)
pd_to_torch

tensor([[1, 3],
        [3, 2],
        [5, 1]])

In [114]:
# pandas series to a numpy array to a tensor
pd_to_torch =  torch.from_numpy(df.values)
pd_to_torch

tensor([[1, 3],
        [3, 2],
        [5, 1]])

In [110]:
# Converting tensor back to pandas
px = pd.DataFrame(pd_to_torch.numpy())
px

0  1
0  1  3
1  3  2
2  5  1

# Indexing and slicing of 2D tensor

In [88]:
# Indexing in 2D
tensor_a[2,2]

tensor(8)

In [89]:
# Indexing in 2D
tensor_a[[2],[2]]

tensor([8])

In [90]:
# Slicing row in 2D 
tensor_a[0,1:3]

tensor([3, 5])

In [91]:
# Slicing column in 2D 
tensor_a[1:3, 0]

tensor([3, 2])

# Basic tensor operations in 2D

In [92]:
x = [[1,3],[3,2]]
tx = torch.tensor(x)
print(tx)

tensor([[1, 3],
        [3, 2]])


In [93]:
y = [[1,3],[3,2]]
ty = torch.tensor(y)
print(ty)

tensor([[1, 3],
        [3, 2]])


In [94]:
tz = tx + ty
tz

tensor([[2, 6],
        [6, 4]])

In [95]:
# Scalar Multiplication 
tx * 3

tensor([[3, 9],
        [9, 6]])

<h3>Element-wise Product/Hadamard Product</h3>

In [111]:
# Vector Multiplication 
# hadamard product - Multiplication of two Matrices or Vectors
tx * ty

tensor([[1, 9],
        [9, 4]])

### Matric Multiplication

In [97]:
p = [[1,3],[3,2],[1,2]]
tp = torch.tensor(p)
tp

tensor([[1, 3],
        [3, 2],
        [1, 2]])

In [98]:
# Matrix dimension
tp.size()

torch.Size([3, 2])

In [99]:
q = [[1,3,2],[1,2,3]]
tq = torch.tensor(q)
tq

tensor([[1, 3, 2],
        [1, 2, 3]])

In [100]:
# Matrix dimension
tq.size()

torch.Size([2, 3])

In [101]:
# Matrix multiplication 3 x 2 and 2 x 3 results in 3 x 3 Matrix
torch.mm(tp,tq)

tensor([[ 4,  9, 11],
        [ 5, 13, 12],
        [ 3,  7,  8]])

# Quiz

In [116]:
X = torch.tensor([[1, 0], [0, 1]])
Y = torch.tensor([[2, 1], [1, 2]]) 
X_times_Y = X * Y
X_times_Y


tensor([[2, 0],
        [0, 2]])